---

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/routes.rb'
    - 'config/initializers/**/*'
    - 'Gemfile'
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

