default: &default
  adapter: postgresql
  pool: <%= Settings.database.pool %>
  host: <%= Settings.database.host %>
  port: <%= Settings.database.port %>
  database: <%= Settings.database.name %>
  username: <%= Settings.database.username %>
  password: <%= Settings.database.password %>
  timeout: 5000

development:
  <<: *default
  database: db_workshop_development

test:
  <<: *default
  database: db_workshop_test

staging:
  <<: *default

production:
  <<: *default
