name: CI
on: [push]

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Rubocop checks
      uses: luizfonseca/github-actions-rubocop@1.5.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
