name: push
on: [push]

env:
  APP_IMAGE_NAME: zipofar/db-workshop

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          cache-to: type=inline
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:cached

      - name: Run Lint
        run: docker-compose -f docker-compose.ci.yml run --rm web bash -c "bundle exec rubocop"
        # run: docker-compose --file docker-compose.test.yml run sut
      - name: Run Test
        run: docker-compose -f docker-compose.ci.yml run --rm web bash -c "RAILS_ENV=test bundle exec rails db:create db:schema:load && bundle exec rails test"



  # test_backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1

  #     - name: Ruby gem cache
  #       uses: actions/cache@v1
  #       with:
  #         path: vendor/bundle
  #         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gems-

  #     - name: Install gems
  #       run: |
  #         bundle config path vendor/bundle
  #         bundle install --jobs 4 --retry 3

  #     - name: Setup test database
  #       env:
  #         RAILS_ENV: test
  #       run: |
  #         bin/rails db:setup

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Install Packages
  #       run: npm install

  #     - name: Compile frontend
  #       env:
  #         RAILS_ENV: test
  #       run: bin/rails webpacker:compile

  #     - name: Run tests
  #       run: bin/rails test
