name: push
on: [push]

env:
  APP_IMAGE_NAME: zipofar/db-workshop

jobs:
  check_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          cache-to: type=inline
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:cached
          build-args: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}

      - name: Run Lint
        run: |
          export WEB_IMAGE=${{ env.APP_IMAGE_NAME }}:cached
          docker-compose -f docker-compose.ci.yml run --rm web bash -c "bundle exec rubocop"

      - name: Run Test
        run: |
          export WEB_IMAGE=${{ env.APP_IMAGE_NAME }}:cached
          docker-compose -f docker-compose.ci.yml run --rm web bash -c "RAILS_ENV=test bundle exec rails db:create && bundle exec rails assets:precompile && DISABLE_SPRING=1 bundle exec rails test"

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest
          build-args: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
